apiVersion: apps/v1
kind: Deployment
metadata:
  name: piojd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piojd
  template:
    metadata:
      labels:
        app: piojd
    spec:
      containers:
      - image: okteto.dev/piojd:latest
        name: piojd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "pixabay.com"
        - name: Vless_UUID
          value: "f4e3bc72-9fc7-4be9-834b-c02053b98852"
        - name: Vless_Path
          value: "/hi111"
        - name: Vmess_UUID
          value: "ab038a56-1c39-451d-9bc9-fca7b2f5b8df"
        - name: Vmess_Path
          value: "/hitt"
        - name: Share_Path
          value: "/kjef33"
